### ISSUE TITLE
Hata mesajlari

### ISSUE THREAD

**Issue by sercanvirlan** [sonsuzdongu/muhafiz#14]
Selam;

Hata mesajlari konusunda bi sorum olucak.

> remote: running php ... Cannot continue commit, please fix these
> remote: Php Linter : PHP Parse error:  syntax error, unexpected ''active'' (T_CONSTANT_ENCAPSED_STRING), expecting ')' in /tmp/kavuq_50fdd26e27c3c_app/abc.php on line 29
> remote: Errors parsing /tmp/kavuq_50fdd26e27c3c_app/abc.php
> To git@xxx.com:yyy/zzz.git
>  ! [remote rejected] master -> master (pre-receive hook declined)
> error: failed to push some refs to 'git@xxx.com:yyy/zzz.git'

Php Linter dan donen hatayi direkt alamiyorum.

> error: failed to push some refs to 'git@xxx.com:yyy/zzz.git'

bu hatayi aliyorum. Runnerlardan donen hatayi almam icin ne yapmaliyim ?

**Comment by yuxel** [comment]
selam,

phplinter'dan dönen hata yukarıda işte?

<pre>
remote: Php Linter : PHP Parse error: syntax error, unexpected ''active'' (T_CONSTANT_ENCAPSED_STRING), expecting ')' in /tmp/kavuq_50fdd26e27c3c_app/abc.php on line 29
 remote: Errors parsing /tmp/kavuq_50fdd26e27c3c_app/abc.php
</pre>

Sorunu tam olarak anlamadım galiba?

**Comment by sercanvirlan** [comment]
PhpStormda sadece failed to push diyor da. Biraz ugrastim console da aliyorum hatayi phpstormda alamiyorum.

**Comment by yuxel** [comment]
Hm, Php storm konusunda tecrübem yok maalesef :(
eğer çözerseniz yeni bir issue açarsanız sevinirim. Bunu kapatıyorum
